
name: Integracion continua practica

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
            java-version: 1.8
      - name: 'Dime la fecha'
        run: echo "Ejecutando un comando en linux"; date
      - name: Build with Maven
        run: mvn -B package --file pom.xml
